<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Frameworktools - devtools - <?=$this->title?></title>
<style type="text/css">
	body {
		font-family: Verdana, Arial, Sans-serif
	}
</style>
</head>
<body>
<h1>Framework  Tools</h1>
<a style="padding-right: 10px;" href="<?=$this->baseUrl()?>/devtools/doctrine/migration">Migration</a>
<br/><br/>
<h3><?=$this->title?></h3>
<?php if(isset($this->message)): ?>
<br/>
<div style="background-color: #EEEEEE; padding: 10px; border: 1px solid black;">
	<?=nl2br(str_replace(' ', '&nbsp;', htmlentities($this->message, ENT_QUOTES, 'UTF-8')))?>
</div><br/>
<?php endif; ?>
<?php
$partialName = $this->partialName;
?>
<?=$this->partial('doctrine/parts/' . $partialName . '.phtml', array('data' => $this->partialData))?>
</body>
</html>