<?=$this->modelList('News_Model_News', array(
    'prefix' => 'news_admin_index_table_',
    'emptyListMessage' => 'news_no_news',
    'showFieldNames' => array(
        'title', 'created_at', 'comments', 'public', 'author'
    ),
    'filterFields' => array(
        'created_at' => array(
            'viewHelper' => 'formatDate',
        ),
        'comments' => array(
            'viewHelper' => 'count'  
        ),
        'public' => array(
            'viewHelper' => 'prefixTranslate',
            'params' => array(
                '_term', true
            )
        )
    ),
    'actions' => array(
    	'comments' => array(
            'image' => '/media/common/images/icons/16/balloon.png',
            'label' => 'news_comments_table_action',
            'privilege' => 'edit',
            'target' => array(
                'module' => 'news',
                'controller' => 'admin',
                'action' => 'comments',
                'params' => array(
                    'id' => '__id__'
                )
            )
        ),
        'edit' => array(
            'image' => '/media/common/images/icons/16/document--pencil.png',
            'label' => 'news_edit_table_action',
            'privilege' => 'edit',
            'target' => array(
                'module' => 'news',
                'controller' => 'admin',
                'action' => 'edit',
                'params' => array(
                    'id' => '__id__'
                )
            )
        ),
        'delete' => array(
            'image' => '/media/common/images/icons/16/document--minus.png',
            'label' => 'news_delete_table_action',
            'privilege' => 'delete',
            'target' => array(
                'module' => 'news',
                'controller' => 'admin',
                'action' => 'delete',
                'params' => array(
                    'id' => '__id__'
                )
            )
        )
    ),
    'footerActions' => array(
        'add' => array(
            'module' => 'news',
            'controller' => 'admin',
            'action' => 'add',
            'label' => $this->translate('add'),
            'image' => '/media/common/images/icons/16/document--plus.png'
        )
    )
), $this->query);?>
