<?php

/**
 * BaseToPrfxUser_Model_UserTask
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $task_id
 * @property integer $user_id
 * @property ToPrfxUser_Model_User $User_Model_User
 * @property ToPrfxUser_Model_Task $User_Model_Task
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseToPrfxUser_Model_UserTask extends FansubCMS_Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('user_tasks');
        $this->hasColumn('task_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ToPrfxUser_Model_User as User_Model_User', array(
             'local' => 'user__model__user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('ToPrfxUser_Model_Task as User_Model_Task', array(
             'local' => 'user__model__task_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}