<?php

/**
 * BaseToPrfxUser_Model_Role
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $role_name
 * @property ToPrfxUser_Model_User $User_Model_User
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseToPrfxUser_Model_Role extends FansubCMS_Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('user_roles');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('role_name', 'string', 255, array(
             'type' => 'string',
             'primary' => true,
             'length' => 255,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ToPrfxUser_Model_User as User_Model_User', array(
             'local' => 'user__model__user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}