<h1><?=$this->translate('imprint_disclaimer')?></h1>
<div class="infobox">
    This is an example imprint! You should change the addresses and texts here to your needs in<span style="font-style:italic;">application/modules/group/views/default/scripts/imprint/index.phtml</span> and the locales.
</div>
<h2><?=$this->translate('imprint')?></h2>
<p><?=$this->translate('law_add')?><br/><br/></p>
<p>Max Mustermann<br />
    Musterstr. 1a<br />
    D-12345 Musterstadt<br />
    <a href="max.mustermann@example.com">max.mustermann@example.com</a>
</p>
<h3><?=$this->translate('contact')?>:</h3><p><?=$this->translate('email')?>: <a href="mailto:contact@example.com">contact@example.com</a></p>
<h3><?=$this->translate('content_admin')?>:</h3>
<p>Beathe Beispielhaft<br />
    Beispielalee 24<br />
    D-54321 Beispielhafthausen<br />
    <a href="mailto:beathe.beispielhaft@example.com">beathe.beispielhaft@example.com</a></p>
<div class="seperator"></div>
<br class="clearfix" />
<h2><?=$this->translate('disclaimer')?></h2>
<?=$this->translate('disclaimer_text')?>