<div class="gadget">
    <div class="gadget-head">
        <?=$this->translate('gadget_project_latest_title')?>
    </div>
    <div class="gadget-body">
        <?php if(count($this->latest)): ?>
        <ul>
        <?php foreach($this->latest as $ep):?>
            <li>
                <?=$this->formatDate($ep->released_at,"longdate")?> - <?=$ep->Project->name?> <?=$ep->number?><?=$ep->version > 1 ? 'v'.$ep->version : ''?> (<?=$ep->vcodec?>)
            </li>
        <?php endforeach; ?>
        </ul>
        <?php else: ?>
        <?=$this->translate('gadget_project_latest_none')?>
        <?php endif; ?>
    </div>
</div>