<div class="gadget">
    <div class="gadget-head">
        <?=$this->translate('gadget_project_random_title')?>
    </div>
    <div class="gadget-body" style="padding:0px;">
        <?php foreach($this->random as $project):?>
        <div class="gadget_project">
            <a href="<?=$this->baseUrl()?>/projects/index/details/project/<?=urlencode($project->name)?>"
               title="<?=$project->name?>">
                <img src="<?=$project->mini_poster?>" width="100%" alt="<?=$project->name?>" />
            </a>
        </div>
        <?php endforeach; ?>
    </div>
</div>