<?=
$this->modelList('User_Model_Task', array(
    'prefix' => 'user_task_list_table_',
    'actions' => array(
        'edit' => array(
            'image' => '/media/common/images/icons/16/wrench--pencil.png',
            'label' => 'user_task_edit_table_action',
            'privilege' => 'edit',
            'target' => array(
                'module' => 'user',
                'controller' => 'admin',
                'action' => 'edittask',
                'params' => array(
                    'id' => '__id__'
                )
            )
        ),
        'delete' => array(
            'image' => '/media/common/images/icons/16/wrench--minus.png',
            'label' => 'user_task_delete_table_action',
            'privilege' => 'delete',
            'target' => array(
                'module' => 'user',
                'controller' => 'admin',
                'action' => 'deletetask',
                'params' => array(
                    'id' => '__id__'
                )
            )
        )
    ),
    'footerActions' => array(
        'add' => array(
            'module' => 'user',
            'controller' => 'admin',
            'action' => 'addtask',
            'label' => $this->translate('add'),
            'image' => '/media/common/images/icons/16/wrench--plus.png'
        )
    )
), $this->query);
