<table>
    <tr>
        <th><?=$this->translate('user_task_list_table_id')?></th>
        <th><?=$this->translate('user_task_list_table_name')?></th>
        <th><?=$this->translate('table_action')?></th>
    </tr>
    <?=$this->partialLoop('partials/taskListLoop.phtml',$this->tasks)?>
</table>
<?php if($this->isAllowed('user_admin','addtask')): ?>
<div class="add"><a href="<?=$this->baseUrl()?>/user/admin/addtask/" class="add2"><img src="<?=$this->baseUrl()?>/images/default/icons/16/wrench--plus.png" alt=""/> <?=$this->translate('add')?></a></div>
<?php endif; ?>
