<?php
	if(!$this->data->generate) {
		$hasChanges = false;
		foreach ($this->data->changes as $changeType => $arr) {
			if(count($arr) > 0) {
				$hasChanges = true;
				break;
			}
		}
		?>
		
		<? if($hasChanges): ?>
			<div style="font-weight: bold;">Es sind geänderte YAML-Models vorhanden.</div>
			<div style="padding-top: 20px;">
				Achtung! Bitte vor der Erstellung der Migrationsklassen sicherstellen, dass zur Zeit niemand sonst das selbe tut!			
			</div><br/>
			<a href="/devtools-admin/doctrine/generatemigrations/generate/1">Migrationsklassen generieren</a><br/><br/><br/>
		<? else: ?>
			Es sind keine geänderten YAML-Models vorhanden. <br/>
		<? endif; ?>
		
		<?
		function dumpArrayRecursive($array, $depth = 0) {
			$first = true;
			foreach($array as $key => $value) {
				if(is_array($value) && ($depth <= 1 && !$first)) {
					echo "<br/>\n";
				}
				
				if(empty($value)) {
					echo "<div style=\"padding-left: " . ($depth * 20) . "px;\">$key: <span style=\"color: #cccccc;\">Leer</span></div>\n"; 	
				}				
				elseif(is_array($value) && count($value) > 0) {
					echo "<div style=\"padding-left: " . ($depth * 20) . "px;\">$key:</div>\n"; 	
					dumpArrayRecursive($value, $depth + 1);
				}
				elseif(is_numeric($value)) {
					echo "<div style=\"padding-left: " . ($depth * 20) . "px;\">{$key}: <span style=\"color: #0000FF;\">{$value}</span></div>\n"; 	
				}
				elseif(is_string($value)) {
					echo "<div style=\"padding-left: " . ($depth * 20) . "px;\">{$key}: <span style=\"color: #FF00FF;\">{$value}</span></div>\n"; 	
				}
				else {
					echo "<div style=\"padding-left: " . ($depth * 20) . "px;\">{$key}: ";
					var_dump($value);
					echo "</div>\n"; 	
				}
				$first = false;
			}
		}
		?>
			<div style="padding: 10px; border: 1px solid black; background-color: #CCCCCC;">
				<? dumpArrayRecursive($this->data->changes); ?>
			</div>
		<?
	}
	else {
		?>
			Migrationsklassen generiert.<br/>
			<br/>
			<a href="/devtools-admin/doctrine/migration">zur Migration</a>
		<?php
	}
?>