<?php
if ($this->data->state == 1) :
if($this->data->append) {
    $url = '/devtools/doctrine/import/append/yes';
    $messageAdd = 'without purge of database';
} else {
    $url = '/devtools/doctrine/import';
    $messageAdd = 'with purge of database';
}
    ?>
<form action="<?php echo $url; ?>" method="post"
	style="padding: 15px; border: 1px solid black; background-color: #CCCCCC;">
<h4>Import data from YAML fixtures to databse <?php echo $messageAdd; ?></h4>
<input type="submit" name="submit" value="Import <?php echo $messageAdd; ?>" /></form>

 <?php 
 elseif ($this->data->state == 2) :
    ?>
	

<?php
endif;
?>