<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('news', 'news_sluggable', array(
             'fields' => 
             array(
              0 => 'title_slug',
             ),
             'type' => 'unique',
             ));
    }

    public function down()
    {
        $this->removeIndex('news', 'news_sluggable', array(
             'fields' => 
             array(
              0 => 'title_slug',
             ),
             'type' => 'unique',
             ));
    }
}