<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('news', 'news_sluggable', array(
             'fields' => 
             array(
              0 => 'title_slug',
             ),
             'type' => 'unique',
             ));
    }
    
    public function postUp()
    {
        $table = Doctrine::getTable('News_Model_News');
        
        $records = $table->findAll();

        foreach($records as $record) {
            if(empty($record->title_slug)) {
                $record->title_slug = Doctrine_Inflector::urlize($record->title);
                $record->save();
            }
        }
    }

    public function down()
    {
        $this->removeIndex('news', 'news_sluggable', array(
             'fields' => 
             array(
              0 => 'title_slug',
             ),
             'type' => 'unique',
             ));
    }
}