<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('projects', 'projects_sluggable', array(
             'fields' => 
             array(
              0 => 'name_slug',
             ),
             'type' => 'unique',
             ));
    }

    public function down()
    {
        $this->removeIndex('projects', 'projects_sluggable', array(
             'fields' => 
             array(
              0 => 'name_slug',
             ),
             'type' => 'unique',
             ));
    }
}