<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('projects', 'name_slug', 'string', '255', array(
             ));

    }
    
    public function down()
    {
        $this->removeColumn('projects', 'name_slug');
    }
}