<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('projects', 'projects_sluggable', array(
             'fields' => 
             array(
              0 => 'name_slug',
             ),
             'type' => 'unique',
             ));
    }

    public function down()
    {
        $this->removeIndex('projects', 'projects_sluggable', array(
             'fields' => 
             array(
              0 => 'name_slug',
             ),
             'type' => 'unique',
             ));
    }
    
    public function postUp()
    {   
        $records = Projects_Model_ProjectTable::getInstance()->findAll();

        foreach($records as $record) {
            if(empty($record->name_slug)) {
                $record->name_slug = Doctrine_Inflector::urlize($record->name);
                $record->save();
            }
        }
    }
}