<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('project_tasks', 'project_tasks_task_id_project_task_types_id', array(
             'name' => 'project_tasks_task_id_project_task_types_id',
             'local' => 'task_id',
             'foreign' => 'id',
             'foreignTable' => 'project_task_types',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('project_tasks', 'project_tasks_user_id_users_id', array(
             'name' => 'project_tasks_user_id_users_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'users',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('project_tasks', 'project_tasks_task_id', array(
             'fields' => 
             array(
              0 => 'task_id',
             ),
             ));
        $this->addIndex('project_tasks', 'project_tasks_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('project_tasks', 'project_tasks_task_id_project_task_types_id');
        $this->dropForeignKey('project_tasks', 'project_tasks_user_id_users_id');
        $this->removeIndex('project_tasks', 'project_tasks_task_id', array(
             'fields' => 
             array(
              0 => 'task_id',
             ),
             ));
        $this->removeIndex('project_tasks', 'project_tasks_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }
}