<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        
        $this->dropTable('project_tasks');
        $this->dropTable('project_task_types');
        $this->createTable('project_chapters', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'project_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'number' => 
             array(
              'type' => 'integer',
              'length' => '5',
             ),
             'version' => 
             array(
              'type' => 'integer',
              'length' => '2',
             ),
             'format' => 
             array(
              'type' => 'string',
              'length' => '10',
             ),
             'resolution' => 
             array(
              'type' => 'string',
              'length' => '10',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'updated_by' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'released_at' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->addColumn('projects', 'project_type', 'enum', '', array(
             'values' => 
             array(
              0 => 'fansub',
              1 => 'scanlation',
             ),
             'default' => 'fansub',
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->createTable('project_task_types', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('project_tasks', array(
             'project_episode_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'project_task_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'project_episode_id',
              1 => 'user_id',
              2 => 'project_task_id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->dropTable('project_chapters');
        $this->removeColumn('projects', 'project_type');
    }
}