<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version10 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('project_screenshots', 'description', 'string', '6000', array(
             ));
        $this->addColumn('project_tasks', 'chapter_id', 'integer', '8', array(
             ));
        $this->addColumn('project_tasks', 'episode_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('project_screenshots', 'description');
        $this->removeColumn('project_tasks', 'chapter_id');
        $this->removeColumn('project_tasks', 'episode_id');
    }
}