<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('project_tasks', 'project_tasks_episode_id_project_episodes_id', array(
             'name' => 'project_tasks_episode_id_project_episodes_id',
             'local' => 'episode_id',
             'foreign' => 'id',
             'foreignTable' => 'project_episodes',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('project_tasks', 'project_tasks_chapter_id_project_chapters_id', array(
             'name' => 'project_tasks_chapter_id_project_chapters_id',
             'local' => 'chapter_id',
             'foreign' => 'id',
             'foreignTable' => 'project_chapters',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('project_tasks', 'project_tasks_episode_id', array(
             'fields' => 
             array(
              0 => 'episode_id',
             ),
             ));
        $this->addIndex('project_tasks', 'project_tasks_chapter_id', array(
             'fields' => 
             array(
              0 => 'chapter_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('project_tasks', 'project_tasks_episode_id_project_episodes_id');
        $this->dropForeignKey('project_tasks', 'project_tasks_chapter_id_project_chapters_id');
        $this->removeIndex('project_tasks', 'project_tasks_episode_id', array(
             'fields' => 
             array(
              0 => 'episode_id',
             ),
             ));
        $this->removeIndex('project_tasks', 'project_tasks_chapter_id', array(
             'fields' => 
             array(
              0 => 'chapter_id',
             ),
             ));
    }
}