<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version13 extends Doctrine_Migration_Base
{   
    public function up()
    {
        $this->createForeignKey('project_chapter_releases', 'project_chapter_releases_chapter_id_project_chapters_id', array(
             'name' => 'project_chapter_releases_chapter_id_project_chapters_id',
             'local' => 'chapter_id',
             'foreign' => 'id',
             'foreignTable' => 'project_chapters',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('project_episode_releases', 'project_episode_releases_episode_id_project_episodes_id', array(
             'name' => 'project_episode_releases_episode_id_project_episodes_id',
             'local' => 'episode_id',
             'foreign' => 'id',
             'foreignTable' => 'project_episodes',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('project_chapter_releases', 'project_chapter_releases_chapter_id', array(
             'fields' => 
             array(
              0 => 'chapter_id',
             ),
             ));
        $this->addIndex('project_episode_releases', 'project_episode_releases_episode_id', array(
             'fields' => 
             array(
              0 => 'episode_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('project_chapter_releases', 'project_chapter_releases_chapter_id_project_chapters_id');
        $this->dropForeignKey('project_episode_releases', 'project_episode_releases_episode_id_project_episodes_id');
        $this->removeIndex('project_chapter_releases', 'project_chapter_releases_chapter_id', array(
             'fields' => 
             array(
              0 => 'chapter_id',
             ),
             ));
        $this->removeIndex('project_episode_releases', 'project_episode_releases_episode_id', array(
             'fields' => 
             array(
              0 => 'episode_id',
             ),
             ));
    }
}