<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version12 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('project_chapter_releases', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'chapter_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'format' => 
             array(
              'type' => 'string',
              'length' => '10',
             ),
             'resolution' => 
             array(
              'type' => 'string',
              'length' => '10',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'updated_by' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'released_at' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('project_episode_releases', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'episode_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'vcodec' => 
             array(
              'type' => 'string',
              'length' => '10',
             ),
             'acodec' => 
             array(
              'type' => 'string',
              'length' => '10',
             ),
             'container' => 
             array(
              'type' => 'string',
              'length' => '10',
             ),
             'crc' => 
             array(
              'type' => 'string',
              'length' => '8',
             ),
             'released_at' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_by' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('project_chapter_releases');
        $this->dropTable('project_episode_releases');
    }
}