<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version16 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('news_comments', 'sourcetype', 'string', '64', array(
             ));
        $this->addColumn('news_comments', 'sourcekey', 'string', '64', array(
             ));
        $this->addColumn('news', 'sourcetype', 'string', '64', array(
             ));
        $this->addColumn('news', 'sourcekey', 'string', '64', array(
             ));
        $this->addColumn('project_chapters', 'sourcetype', 'string', '64', array(
             ));
        $this->addColumn('project_chapters', 'sourcekey', 'string', '64', array(
             ));
        $this->addColumn('project_chapter_releases', 'sourcetype', 'string', '64', array(
             ));
        $this->addColumn('project_chapter_releases', 'sourcekey', 'string', '64', array(
             ));
        $this->addColumn('project_episodes', 'sourcetype', 'string', '64', array(
             ));
        $this->addColumn('project_episodes', 'sourcekey', 'string', '64', array(
             ));
        $this->addColumn('project_episode_releases', 'sourcetype', 'string', '64', array(
             ));
        $this->addColumn('project_episode_releases', 'sourcekey', 'string', '64', array(
             ));
        $this->addColumn('projects', 'sourcetype', 'string', '64', array(
             ));
        $this->addColumn('projects', 'sourcekey', 'string', '64', array(
             ));
        $this->addColumn('project_screenshots', 'sourcetype', 'string', '64', array(
             ));
        $this->addColumn('project_screenshots', 'sourcekey', 'string', '64', array(
             ));
        $this->addColumn('users', 'sourcetype', 'string', '64', array(
             ));
        $this->addColumn('users', 'sourcekey', 'string', '64', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('news_comments', 'sourcetype');
        $this->removeColumn('news_comments', 'sourcekey');
        $this->removeColumn('news', 'sourcetype');
        $this->removeColumn('news', 'sourcekey');
        $this->removeColumn('project_chapters', 'sourcetype');
        $this->removeColumn('project_chapters', 'sourcekey');
        $this->removeColumn('project_chapter_releases', 'sourcetype');
        $this->removeColumn('project_chapter_releases', 'sourcekey');
        $this->removeColumn('project_episodes', 'sourcetype');
        $this->removeColumn('project_episodes', 'sourcekey');
        $this->removeColumn('project_episode_releases', 'sourcetype');
        $this->removeColumn('project_episode_releases', 'sourcekey');
        $this->removeColumn('projects', 'sourcetype');
        $this->removeColumn('projects', 'sourcekey');
        $this->removeColumn('project_screenshots', 'sourcetype');
        $this->removeColumn('project_screenshots', 'sourcekey');
        $this->removeColumn('users', 'sourcetype');
        $this->removeColumn('users', 'sourcekey');
    }
}