<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('projects', 'element_count', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('projects', 'element_count');
    }
}