<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version18 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('news', 'publish_date', 'timestamp', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('news', 'publish_date');
    }
    
    public function postUp()
    {
        parent::postUp();
        
        // Set dates for all existing news
        $news = News_Model_NewsTable::getInstance()->findAll();
               
        foreach($news as $article) {
            if($article->public == 'yes') {
                $article->publish_date = $article->created_at;
                $article->save();
            }
        }
    }
}