<?=$this->partial('partials/quickselect.phtml',$this->quickSelect)?>
<?php if($this->project): ?>
<h1><?=$this->project->name?></h1>
<h2><?=$this->project->name_jp?></h2>
<div class="poster">
    <img src="<?=$this->project->poster?>" alt="<?=$this->project->name?>" />
</div>
<div class="seperator"></div>
<br class="clearfix" />
<h3><?=$this->translate('project_description')?></h3>
<?php $status = 'project_status_'.$this->project->status; ?>
<span class="project-status-desc"><?=$this->translate('project_status')?></span>
<span class="<?=$status?>"><?=$this->translate($status)?></span><br />
<span class="project-status-desc"><?=$this->translate('project_episodes')?></span>
<span class="project-epsiode-count"><?=$this->project->getReleaseEpisodeCount()?> / <?=empty($this->project->element_count) ? $this->translate('project_episode_unknown_count') : $this->project->element_count ?></span>
<div><?=$this->textile($this->project->description)?></div>
<div class="seperator"></div>
<br class="clearfix" />
<h3><?=$this->translate('project_screenshot')?></h3>
    <?php if(count($this->project->Projects_Model_Screenshot)):?>
    <?php foreach($this->project->Projects_Model_Screenshot as $screenshot):?>
    <a href="<?=$screenshot->screenshot?>" rel="shadowbox[Screenshot]">
        <img class="screenshot" src="<?=$screenshot->screenshot?>" alt="" />
    </a>
    <?php endforeach; ?>
    <?php else: ?>
    <?=$this->translate('project_no_screenshot')?>
    <?php endif; ?>
<div class="seperator"></div>
<br class="clearfix" />
<?php if(count($this->project->Projects_Model_Leader) || count($this->project->Projects_Model_User)): ?>
<h3><?=$this->translate('project_team')?></h3>
<?php if(count($this->project->Projects_Model_Leader)): ?>
<h4><?=$this->translate('project_team_management')?></h4>
<?php foreach($this->project->Projects_Model_Leader as $leader): ?>
<?=$leader->User_Model_User->name?><br />
<?php endforeach; ?>
<?php endif; ?>
<?php if(count($this->project->Projects_Model_User)): ?>
<h4><?=$this->translate('project_team_members')?></h4>
<?php foreach($this->project->Projects_Model_User as $member): ?>
<?=$member->User_Model_User->name?> - <?=$member->function?><br />
<?php endforeach; ?>
<?php endif; ?>
<div class="seperator"></div>
<br class="clearfix" />
<?php endif; ?>
<h3><?=$this->translate('project_episodes')?></h3>
<table>
    <tr>
        <th><?=$this->translate('project_episode_number')?></th>
        <th><?=$this->translate('project_episode_title')?></th>
        <th><?=$this->translate('project_episode_crc')?></th>
        <th><?=$this->translate('project_episode_date')?></th>
        <th><?=$this->translate('project_episode_info')?></th>
    </tr>
    <?php if(count($this->project->getReleasedEpisodes())):?>
    <?=$this->partialLoop('partials/projectEpisodeLoop.phtml',$this->project->getReleasedEpisodes())?>
    <?php else: ?>
    <tr>
        <td colspan="5"><?=$this->translate('project_no_episode')?></td>
    </tr>
    <?php endif; ?>
</table>
<?php else: ?>
<?=$this->translate('project_not_exist', array('name' => $this->projectName))?>
<?php endif; ?>