<?php if(count($this->projects)):?>
<?=$this->partial('partials/quickselect.phtml',$this->quickSelect)?>
<div class="seperator"></div>
<?php foreach($this->projects as $status => $projects): ?>
<?php if(empty($projects)) continue; ?>
<h1><?=$this->translate('project_status_' . $status)?></h1>
<br /><br />
<?=$this->partialLoop('partials/projectLoop.phtml',$projects)?>
<?php endforeach; ?>
<?=$this->partial('partials/quickselect.phtml',$this->quickSelect)?>
<?php else: ?>
<?=$this->translate('project_no_projects')?>
<?php endif;?>