<?php if($this->isAllowed($this->project, 'editteammember')): ?>
    <a href="<?=$this->baseUrl('/projects/admin/editteammember/pid/'.$this->member->project_id.'/uid/'.$this->member->user_id)?>" title="<?=$this->escape($this->translate('update')) ?>">
        <img src="<?=$this->baseUrl('/media/common/images/icons/16/wrench.png')?>" alt="" /> 
    </a>
<?php endif; ?>
<?php if($this->isAllowed($this->project, 'deleteteammember')): ?>
    <a href="<?=$this->baseUrl('/projects/admin/deleteteammember/pid/'.$this->member->project_id.'/uid/'.$this->member->user_id)?>" title="<?=$this->escape($this->translate('delete'))?>">
        <img src="<?=$this->baseUrl('/media/common/images/icons/16/minus.png')?>" alt="" /> 
    </a>
<?php endif; ?>