<?php

/**
 * Projects_Model_Episode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    FansubCMS
 * @subpackage Models
 * @author     FansubCMS Dev Team <hikaru@fansubcode.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Projects_Model_Episode extends Projects_Model_Base_Episode
{
   
    public function updateEpisode ($values)
    {
        if (! empty($values['project']))
            $this->project_id = $values['project'];
        if (! empty($values['title']))
            $this->title = $values['title'];
        if (! empty($values['number']))
            $this->number = $values['number'];
        if (! empty($values['version']))
            $this->version = $values['version'];
        $this->save();
    }
}