<?php

/**
 * Projects_Model_EpisodeRelease
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    FansubCMS
 * @subpackage Models
 * @author     FansubCMS Dev Team <hikaru@fansubcode.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Projects_Model_EpisodeRelease extends Projects_Model_Base_EpisodeRelease
{
    public function getUpdater()
    {
        if (empty($this->updated_by)) {
            return false;
        }
        $q = Doctrine_Query::create();
        $q->from('User_Model_User u')->where('u.id = ?', $this->updated_by);
        $u = $q->fetchOne();

        if(!$u) {
            $this->set('updated_by', new Doctrine_Null());
            $this->save();
            return false; // user seems to be deleted
        }
        
        return $u->name;
    }
    
    public function updateRelease($values)
    {
        if(!empty($values['container']))
            $this->container = $values['container'];
        if(!empty($values['vcodec']))
            $this->vcodec = $values['vcodec'];
        if(!empty($values['acodec']))
            $this->acodec = $values['acodec'];
        if(!empty($values['crc']))
            $this->crc = $values['crc'];
        if(!empty($values['released']) && $values['released'] == 'yes') {
            if (empty($values['isoDate'])) {
                $this->released_at = date('Y-m-d H:i:s');
            } else {
                $this->released_at = $values['isoDate'];
            }
        } else if (!empty($values['released']) && $values['released'] == 'no') {
                $this->released_at = null;
        }
        
        $this->updated_by = Zend_Auth::getInstance()->getIdentity()->id;
        $this->save();
    }
}