<?php

/**
 * Projects_Model_Project
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    FansubCMS
 * @subpackage Models
 * @author     FansubCMS Dev Team <hikaru@fansubcode.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Projects_Model_Project extends Base_Projects_Model_Project
{
    private $_released;
    public function getReleasedEpisodes ()
    {
        if (is_null($this->_released)) {
            $pet = Doctrine::getTable('Projects_Model_Episode');
            $q = $pet->buildQueryForListing('number ASC');
            $q->where('released_at IS NOT NULL')->andWhere(
            'project_id = ?', $this->id);
            $this->_released = $q->fetchArray();
        }
        return $this->_released;
    }
    public function updateProject (array $values)
    {
        if (! empty($values['name']))
            $this->name = $values['name'];
        if (! empty($values['name_jp']))
            $this->name_jp = $values['name_jp'];
        if (! empty($values['poster']))
            $this->poster = $values['poster'];
        if (! empty($values['mini_poster']))
            $this->mini_poster = $values['mini_poster'];
        if (! empty($values['description']))
            $this->description = $values['description'];
        if (! empty($values['status']))
            $this->status = $values['status'];
        if (! empty($values['private']))
            $this->private = $values['private'];
        $this->save();
    }
}