<?php

/**
 * Projects_Model_Screenshot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    FansubCMS
 * @subpackage Models
 * @author     FansubCMS Dev Team <hikaru@fansubcode.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Projects_Model_Screenshot extends Base_Projects_Model_Screenshot
{
    public function updateScreenshot ($values)
    {
        if (! empty($values['project']))
            $this->project_id = $values['project'];
        if (! empty($values['description']))
            $this->description = $values['description'];
        if ($values['file'] instanceof Zend_Form_Element_File) {
            $file = $values['file']->receive();
            if (! $file) {
                throw new Zend_Exception(
                'There was an error with the file upload.');
            }
            
            if (! empty($this->screenshot)) {
                $file = explode('/', $this->screenshot);
                $file = $file[count($file) - 1];
                @unlink(
                realpath(UPLOAD_PATH . '/screenshots/') . DIRECTORY_SEPARATOR .
                 $file);
            }
            $view = Zend_Layout::getMvcInstance()->getView();
            $this->screenshot = $view->baseUrl() . '/upload/screenshots/' .
             $values['screen'];
        }
        $this->save();
    }
    public function delete (Doctrine_Connection $conn = null)
    {
        $file = explode('/', $this->screenshot);
        $file = $file[count($file) - 1];
        $file = realpath(UPLOAD_PATH . '/screenshots/') . DIRECTORY_SEPARATOR .
         $file;
        if (is_file($file)) {
            unlink($file);
        } else {
            throw new Zend_Exception('File to delete does not exist.');
        }
        parent::delete($conn);
    }
}