<?php

/**
 * Projects_Model_TaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Projects_Model_TaskTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Projects_Model_TaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Projects_Model_Task');
    }
}