<?= $this->partial('partials/datepicker.phtml', array('identifier' => '#releasedate', 'altIdentifier' => '#isoDate')) ?>
<h1><?= $this->translate('project_addepisode_headline') ?></h1>
<?= $this->form ?>
<script type="text/javascript">
    $("input[name='released']").click(checkChange);
    function checkChange() {
        if($("input[name='released']:checked").val() == "yes") {
            $("#releasedate").removeAttr("disabled");
        } else {
            $("#releasedate").attr("disabled", "disabled");
        }
    }
    checkChange();
</script>