<?php
$fields = array();
if(!empty($this->all)) {
    $fields = array('project');
}
$fields = array_merge($fields, array(
    'number', 'version', 'name'
));
echo $this->modelList('Projects_Model_Episode', array(
    'prefix' => 'project_admin_episode_table_',
    'emptyListMessage' => 'project_no_episode',
    'showFieldNames' => $fields,
    'filterFields' => array(
        /*'released_at' => array(
            'viewHelper' => 'formatDate',
            'params' => array(
                'date'
            ),
            'emptyText' => 'no_term'
        ),
        'codec' => array(
            'viewHelper' => 'container',
            'passRecord' => true
        )*/
    ),
    'actions' => array(
        'edit' => array(
            'image' => '/media/common/images/icons/16/monitor--pencil.png',
            'label' => 'project_edit_table_action',
            'privilege' => 'edit',
            'target' => array(
                'module' => 'projects',
                'controller' => 'admin',
                'action' => 'editepisode',
                'params' => array(
                    'id' => '__id__'
                )
            )
        ),
        'delete' => array(
            'image' => '/media/common/images/icons/16/monitor--minus.png',
            'label' => 'project_delete_table_action',
            'privilege' => 'delete',
            'target' => array(
                'module' => 'projects',
                'controller' => 'admin',
                'action' => 'deleteepisode',
                'params' => array(
                    'id' => '__id__'
                )
            )
        )
    ),
    'footerActions' => array(
        'add' => array(
            'module' => 'projects',
            'controller' => 'admin',
            'action' => 'addepisode',
            'label' => $this->translate('add'),
            'image' => '/media/common/images/icons/16/monitor--plus.png'
        )
    )
), $this->query);
