<?=
$this->modelList('Projects_Model_Screenshot', array(
    'prefix' => 'project_admin_screenshot_table_',
    'emptyListMessage' => 'project_no_screenshot',
    'showFieldNames' => array(
       'id', 'description', 'screen', 'project',
    ),
    'actions' => array(
        'edit' => array(
            'image' => '/media/common/images/icons/16/picture--pencil.png',
            'label' => 'project_edit_table_action',
            'privilege' => 'edit',
            'target' => array(
                'module' => 'projects',
                'controller' => 'admin',
                'action' => 'editscreenshot',
                'params' => array(
                    'id' => '__id__'
                )
            )
        ),
        'delete' => array(
            'image' => '/media/common/images/icons/16/picture--minus.png',
            'label' => 'project_delete_table_action',
            'privilege' => 'delete',
            'target' => array(
                'module' => 'projects',
                'controller' => 'admin',
                'action' => 'deletescreenshot',
                'params' => array(
                    'id' => '__id__'
                )
            )
        )
    ),
    'footerActions' => array(
        'add' => array(
            'module' => 'projects',
            'controller' => 'admin',
            'action' => 'addscreenshot',
            'label' => $this->translate('add'),
            'image' => '/media/common/images/icons/16/picture--plus.png'
        )
    )
), $this->query);
