<?=
$this->modelList('Projects_Model_Task', array(
    'prefix' => 'project_admin_task_table_',
    'emptyListMessage' => 'project_no_tasks',
    'showFieldNames' => array(
       'id', 'type_title', 'comment', 'done', 'username', 'number', 'version'
    ),
    'filterFields' => array(
        'done' => array(
            'viewHelper' => 'prefixTranslate',
            'params' => array(
                '%', true
            )
        ),
    ),
    'actions' => array(
        'edit' => array(
            'image' => '/media/common/images/icons/16/wrench--pencil.png',
            'label' => 'project_edit_table_action',
            'privilege' => 'edit-task',
            'target' => array(
                'module' => 'projects',
                'controller' => 'admin',
                'action' => 'edit-task',
                'params' => array(
                    'id' => '__id__'
                )
            )
        ),
        'delete' => array(
            'image' => '/media/common/images/icons/16/wrench--minus.png',
            'label' => 'project_delete_table_action',
            'privilege' => 'delete-task',
            'target' => array(
                'module' => 'projects',
                'controller' => 'admin',
                'action' => 'delete-task',
                'params' => array(
                    'id' => '__id__'
                )
            )
        )
    ),
    'footerActions' => array(
        'add' => array(
            'module' => 'projects',
            'controller' => 'admin',
            'action' => 'add-task',
            'label' => 'add',
            'image' => '/media/common/images/icons/16/wrench--plus.png',
            'params' => array(
                'pid' => $this->project->id
            )
        )
    )
), $this->query);