<?php
/*
 * This file is part of FansubCMS.
 *
 *  FansubCMS is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  FansubCMS is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with FansubCMS.  If not, see <http://www.gnu.org/licenses/>
 */

/**
 * NewsComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    FansubCMS
 * @subpackage Models
 * @author     FansubCMS Developer <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
class NewsComment extends BaseModelNewsComment
{
    /**
     * Die Settermethode für URL
     * @author Hikaru-Shindo <hikaru@animeownage.de>
     * @param string $url
     */
    public function setUrl($url) {
        $url = urldecode($url);
        if(!stristr($url,'http://') && !stristr($url,'https://') && !empty($url)) $url = 'http://'.$url;
        $this->_set('url',$url);    
    }
    
    /**
     * Die Settermethode für Comments
     * @author Hikaru-Shindo <hikaru@animeownage.de>
     * @param string $comment
     */
    public function setComment($comment) {
        $comment = str_replace('\xC2\xA0',' ',$comment); // nbsp ersetzen durch normanel space
        $comment = trim($comment,'\n'); // string trimmen
        $this->_set('comment',$comment);
    }	
    
    public function checkSpam($mark = true) {
    	$a = new FansubCMS_Validator_Akismet();
    	$a = $a->getAkismet();
    	$a->setCommentAuthor($this->author);
    	$a->setCommentAuthorEmail($this->email);
    	$a->setCommentAuthorURL($this->url);
    	$a->setCommentContent($this->comment);
    	$a->setUserIP($this->ip);
    	$a->setReferrer(getenv('HTTP_REFERER'));
    	$status = $a->isCommentSpam();
    	if($mark === true ) {
    		$status ? $set = 'yes' : $set = 'no';
    		$this->_set('spam',$set);
    	}
    	return $status;
    }
}