<?php

/**
 * News
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    FansubCMS
 * @subpackage Models
 * @author     FansubCMS Developer <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
class News extends BaseModelNews {
	/**
	 * get News
	 * @param integer $limit
	 * @param integer $offset
	 * @param bool | null $public
	 * @return Doctrine_Collection
	 */
    static function getNews($limit,$offset,$public=true) {
        $q = Doctrine_Query::create();
        $q->from('News n')
        ->limit($limit) 
        ->offset($offset);
        if($public === false) {
        	$q->where('public = ?','no');
        } else if($public === true) {
        	$q->where('public = ?','yes');
        }
        return $q->execute();
    }

    /**
     * get one news by its id
     * @param integer $id
     * @return News
     */
    static function getNewsById($id) {
        $q = Doctrine_Query::create();
        $q->from('News n')
          ->where('id = ?',$id);
        return $q->fetchOne();
    }
    
    /**
     * gets comments that are not marked as spam or invisible
     * @return Doctrine_Collection
     */
    public function getComments() {
    	$q = Doctrine_Query::create();
    	$q->from('NewsComment nc')
    	  ->where('spam = ?','no')
    	  ->andWhere('visible = ?','yes')
          ->andWhere('news_id = ?',$this->id)
    	  ->orderBy('nc.created_at DESC');;
        return $q->execute();
    }
    
    /**
     * returns a Zend_Paginator_Object
     * @see Zend_Paginator
     * @param mixed $spam true spam false non-spam everything else all
     * @param mixed $visible true visible false invisible everything else all
     * @return Zend_Paginator
     */
    public function getCommentPaginator($spam=null,$visible=null) {
        $q = Doctrine_Query::create();
        $q->from('NewsComment nc')
          ->orderBy('nc.created_at DESC');
        
        if($spam === true) {
            $q->andWhere('nc.spam = ?','yes');
        } else if($spam === false) {
            $q->andWhere('nc.spam = ?','no');
        }
        if($visible === true) {
            $q->andWhere('nc.visible = ?','yes');
        } else if($visible === false) {
            $q->andWhere('nc.visible = ?','no');
        }
        $q->andWhere('nc.news_id = ?',$this->id);
        
        $adapter = new FansubCMS_Paginator_Adapter_Doctrine($q);
        return new Zend_Paginator($adapter);
    }
}