<?php

/**
 * ProjectEpisode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    FansubCMS
 * @subpackage Models
 * @author     FansubCMS Developer <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
class ProjectEpisode extends BaseModelProjectEpisode
{
    public function getUpdater() {
        if(empty($this->updated_by)) {
            return false;
        }

        $q = Doctrine_Query::create();
        $q->from('User u')
          ->where('u.id = ?',$this->updated_by);
        $u = $q->fetchOne();
        return $u->name;
    }

    public function updateEpisode($values) {
         if(!empty($values['project']))
            $this->project_id = $values['project'];
        if(!empty($values['title']))
            $this->title = $values['title'];
        if(!empty($values['number']))
            $this->number = $values['number'];
        if(!empty($values['version']))
            $this->version = $values['version'];
        if(!empty($values['container']))
            $this->container = $values['container'];
        if(!empty($values['vcodec']))
            $this->vcodec = $values['vcodec'];
        if(!empty($values['acodec']))
            $this->acodec = $values['acodec'];
        if(!empty($values['crc']))
            $this->crc = $values['crc'];
        if(!empty($values['released']) && $values['released'] == 'yes' && empty($this->released_at)) {
            $this->released_at = date('Y-m-d H:i:s');
        } else if(!empty($values['released']) && $values['released'] == 'no') {
            $this->released_at = null;
        }
        $this->updated_by = Zend_Auth::getInstance()->getIdentity()->id;
        $this->save();
    }
}