<?php
/*
 * This file is part of FansubCMS.
 *
 *  FansubCMS is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  FansubCMS is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with FansubCMS.  If not, see <http://www.gnu.org/licenses/>
 */

/**
 * Project
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    FansubCMS
 * @subpackage Models
 * @author     FansubCMS Developer <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
class Project extends BaseModelProject {
    private $_released;

    public function getReleasedEpisodes() {
        if(is_null($this->_released)) {
            $pet = Doctrine::getTable('ProjectEpisode');
            $q = $pet->buildQueryForListing('number ASC');
            $q->where('pe.released_at IS NOT NULL')
              ->andWhere('pe.project_id = ?',$this->id);
            $this->_released = $q->fetchArray();
        }
        return $this->_released;
    }

    public function updateProject(array $values) {
        if(!empty($values['name']))
            $this->name = $values['name'];
        if(!empty($values['name_jp']))
            $this->name_jp = $values['name_jp'];
        if(!empty($values['poster']))
            $this->poster = $values['poster'];
        if(!empty($values['mini_poster']))
            $this->mini_poster = $values['mini_poster'];
        if(!empty($values['description']))
            $this->description = $values['description'];
        if(!empty($values['status']))
            $this->status = $values['status'];
        if(!empty($values['private']))
            $this->private = $values['private'];
        $this->save();
    }
}