<?php

/**
 * Project
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    FansubCMS
 * @subpackage Models
 * @author     FansubCMS Developer <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
class Project extends BaseModelProject {
    private $_released;

    public function getReleasedEpisodes() {
        if(is_null($this->_released)) {
            $pet = Doctrine::getTable('ProjectEpisode');
            $q = $pet->buildQueryForListing('number ASC');
            $q->where('pe.released_at IS NOT NULL')
              ->andWhere('pe.project_id = ?',$this->id);
            $this->_released = $q->fetchArray();
        }
        return $this->_released;
    }

    public function updateProject(array $values) {
        if(!empty($values['name']))
            $this->name = $values['name'];
        if(!empty($values['name_jp']))
            $this->name_jp = $values['name_jp'];
        if(!empty($values['poster']))
            $this->poster = $values['poster'];
        if(!empty($values['mini_poster']))
            $this->mini_poster = $values['mini_poster'];
        if(!empty($values['description']))
            $this->description = $values['description'];
        if(!empty($values['status']))
            $this->status = $values['status'];
        if(!empty($values['private']))
            $this->private = $values['private'];
        $this->save();
    }
}