<?php
/*
 *  This file is part of FansubCMS.
 *
 *  FansubCMS is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  FansubCMS is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with FansubCMS.  If not, see <http://www.gnu.org/licenses/>
 */

/**
 * UserRole
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    FansubCMS
 * @subpackage Models
 * @author     FansubCMS Developer <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UserRole extends BaseModelUserRole
{
    static private $_roles = null;

    public static function getRoles() {
        if(!isset(self::$_roles)) {
            $cm = Zend_Registry::get('Zend_Cache_Manager');
            $cache = $cm->getCache('FansubCMS');
            $config = $cache->load('Acl_Settings');
            foreach($config as $module => $modconf) {
                if(empty($modconf['roles'])) {
                    continue;
                }
                foreach($modconf['roles'] as $role) {
                    self::$_roles[$role['role']] = $module.'_role_'.$role['role'];
                }
                asort(self::$_roles);
            }
        }
        return self::$_roles;
    }
}