<?php

/**
 * User_Model_Role
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    FansubCMS
 * @subpackage Models
 * @author     FansubCMS Dev Team <hikaru@fansubcode.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User_Model_Role extends Base_User_Model_Role
{
    private static $_roles = null;
    public static function getRoles ()
    {
        if (! isset(self::$_roles)) {
            $ch = FansubCMS_Cache_Helper::getInstance();
            $cache = $ch->getCache('Acl_Settings');
            $config = $cache->load('Acl');
            foreach ($config as $module => $modconf) {
                if (empty($modconf['roles'])) {
                    continue;
                }
                foreach ($modconf['roles'] as $role) {
                    self::$_roles[$role['role']] = $module . '_role_' .
                     $role['role'];
                }
                asort(self::$_roles);
            }
        }
        return self::$_roles;
    }
}