<?php

/**
 * User_Model_TaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class User_Model_TaskTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object User_Model_TaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User_Model_Task');
    }
    
    public function getTasks ()
    {
        $tasks = $this->findAll(Doctrine_Core::HYDRATE_ARRAY);
        $return = array();
        foreach ($tasks as $task) {
            $return[$task['id']] = $task['name'];
        }
        return $return;
    }
}