<?php

/**
 * Projects_Model_Base_EpisodeRelease
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $episode_id
 * @property string $vcodec
 * @property string $acodec
 * @property string $container
 * @property string $crc
 * @property timestamp $released_at
 * @property string $updated_by
 * @property string $sourcetype
 * @property string $sourcekey
 * @property Projects_Model_Episode $Projects_Model_Episode
 * 
 * @package    FansubCMS
 * @subpackage Models
 * @author     FansubCMS Dev Team <hikaru@fansubcode.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Projects_Model_Base_EpisodeRelease extends FansubCMS_Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('project_episode_releases');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('episode_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('vcodec', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('acodec', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('container', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('crc', 'string', 8, array(
             'type' => 'string',
             'length' => 8,
             ));
        $this->hasColumn('released_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('updated_by', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('sourcetype', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('sourcekey', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));


        $this->index('eprel_src_idx', array(
             'fields' => 
             array(
              0 => 'sourcetype',
              1 => 'sourcekey',
             ),
             ));
        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Projects_Model_Episode', array(
             'local' => 'episode_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}