<script type="text/javascript" src="<?=$this->baseUrl()?>/lib/markitup/jquery.markitup.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl()?>/lib/markitup/sets/default/set.js"></script>
<script type="text/javascript" >
   $(document).ready(function() {
      $("#text").markItUp(mySettings);
   });
</script>
<h1><?=$this->translate('cms_add_static_headline')?></h1>
<?=$this->form?>