<?=$this->doctype()?>
<html>
<head>
<title><?=$this->translate('install_title')?></title>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<?php
$this->headScript()->appendFile($this->baseUrl().'/lib/jquery/jquery-1.4.2.min.js', 'text/javascript', array());
echo $this->headScript()->appendFile($this->baseUrl().'/lib/common.js', 'text/javascript', array());
?>
<style type="text/css">
body {
	background-color: #D6D3C4;
	color: #1f211f;
	text-align: center; /* horizontal centering for IE Win quirks */
}

html, body {
	height:100%;
}

* {
	margin: 0;
	padding: 0;
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
}

#distance {
	width: 1px;
	height: 50%;
	background-color: #a1a1a1;
	margin-bottom: -150px; /* half of the container height */
	float: left;
}

#container {
	margin: 0 auto;
	position: relative; /* puts the container in front of distance */
	height: 300px;
	width: 550px;
	clear: left;
	background-color: #A4AA9C;
	border: solid 2px;
	border-color: #B98675;
}

h1 {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 20px;
	text-align: center;
	background-color: #7C8982;
}

h2 {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 15px;
	text-align: left;
	padding-top: 10px;
	padding-left: 10px;
}

p {
	font-family:Arial, Helvetica, sans-serif;
	font-size:12px;
	padding-left:20px;
	margin:10px;
}

.content {
	padding-top: 5px;
	padding-left: 10px;
	text-align: left;
}

.status {
	border: black solid 1px;
	background-color: #CCCCCC;
	margin: 10px;
	padding: 5px;
}

.button {
	background-color:#c8c8c8; 
	border:solid 1px; 
	border-color:#B98675;
}

input.button:hover{
   color:#B98675;
} 

#submit {
	background-color:#c8c8c8; 
	border:solid 1px; 
	border-color:#B98675;
}

input.submit:hover{
   color:#B98675;
}
</style>
</head>
<body>