<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
        <title><?= $this->layout()->group ?> - <?= $this->translate('administration') ?></title>
        <?php
        $sess = Zend_Registry::get('applicationSessionNamespace');
        $this->headLink()->appendStylesheet($this->baseUrl() . "/themes/shadowbox.css")
        ->appendStylesheet($this->baseUrl()."/themes/default/jquery-ui/darkness/jquery-ui-1.8.7.css")
        ->appendStylesheet($this->baseUrl() . "/themes/default/common.css")
        ->appendStylesheet($this->baseUrl() . "/themes/default/admin.css");
        if($sess->markitup == 'html') {
            $this->headLink()->appendStylesheet($this->baseUrl() . "/lib/markitup/sets/default/style.css");
        } else {
            $this->headLink()->appendStylesheet($this->baseUrl() . "/lib/markitup/sets/textile/style.css");
        }
        echo $this->headLink()->appendStylesheet($this->baseUrl() . "/lib/markitup/skins/markitup/style.css");

        echo $this->headScript()->appendFile($this->baseUrl() . '/lib/jquery/jquery-1.4.4.min.js', 'text/javascript', array())
        ->appendFile($this->baseUrl() . '/lib/jquery/jquery-ui-1.8.7.min.js', 'text/javascript', array())
        ->appendFile('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.7/i18n/jquery-ui-i18n.min.js', 'text/javascript', array())
        ->appendFile($this->baseUrl() . '/lib/jquery/shadowbox.js', 'text/javascript', array())
        ->appendFile($this->baseUrl() . '/lib/common.js', 'text/javascript', array());
        ?>
        <script type="text/javascript">
            Shadowbox.init({
                // a darker overlay looks better on this particular site
                overlayOpacity: 0.8
            });
        </script>
    </head>
    <body>
        <div id="root">
            <div id="header">
            </div>
            <div class="spacer gray"></div>
            <div>
                <br class="clearfix" />
                <div id="admin-menu">
                    <?= $this->navigation()->setAcl(Zend_Registry::get('Zend_Acl'))->setRole('fansubcms_user_custom_role_logged_in_user')->menu()->renderMenu() ?>
                </div>
                <div id="content">
                    <?php if (isset($this->message)): ?>
                        <div class="success">
                        <?= $this->message ?>
                    </div>
                    <br class="clearfix" />
                    <?php endif; ?>
                    <?= $this->layout()->content ?>
                </div>
            </div>
            <br class="clearfix" />
            <div id="footer">
                &copy; 2010 by Hikaru-Shindo<br/>
                &copy; Design by punkid
            </div>
        </div>
    </body>
</html>
