<?=$this->doctype()?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?=$this->layout()->language?>" lang="<?=$this->layout()->language?>">
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<title><?=$this->layout()->group?></title>
        <?php
        echo $this->headLink()
            ->appendStylesheet($this->baseUrl() . "/media/common/css/shadowbox.css")
            ->appendStylesheet(
        $this->baseUrl() .
         "/media/common/css/jquery-ui/darkness/jquery-ui-1.8.7.css")
            ->appendStylesheet($this->baseUrl() . "/media/default/css/common.css")
            ->appendStylesheet(
        $this->baseUrl() . "/media/default/css/frontend.css");
        echo $this->headScript()
            ->appendFile($this->baseUrl() . '/media/common/js/jquery/jquery-1.4.4.min.js',
        'text/javascript', array())
            ->appendFile(
        $this->baseUrl() . '/media/common/js/jquery/jquery-ui-1.8.7.min.js',
        'text/javascript', array())
            ->appendFile(
        'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.7/i18n/jquery-ui-i18n.min.js',
        'text/javascript', array())
            ->appendFile($this->baseUrl() . '/media/common/js/jquery/shadowbox.js',
        'text/javascript', array())
            ->appendFile($this->baseUrl() . '/media/common/js/common.js', 'text/javascript',
        array());
        ?>
        <script type="text/javascript">
            Shadowbox.init({
                // a darker overlay looks better on this particular site
                overlayOpacity: 0.8
            });
        </script>
</head>
<body>
<div id="root">
<div id="header"></div>
<div class="menu">
<div id="menu">
                    <?=$this->navigation()->menu()->renderMenu(null, array("renderParents" => true, 'minDepth' => 0, 'maxDepth' => 0))?>
                </div>
</div>
<div id="layout-content">
                <?php
                if (isset($this->message)) :
                    ?>
                <div class="infobox">
                        <?=$this->message?>
                </div>
                
                <?php endif;
                ?>
                <div class="box fullwidth">
                    <?=$this->layout()->content?>
                </div>
</div>
<div id="gadgets">
                <?php
                // show the gadgets, that were configured
                if (is_array($this->gadgets)) {
                    foreach ($this->gadgets as $gadget) {
                        $content = $this->action($gadget['action'], $gadget['name'], 
                        'gadgets', $gadget['params']);
                        
                        echo $this->partial('partials/gadgetLayout.phtml', array(
                            'label' => $gadget['label'],
                            'content' => $content
                        ));
                    } 
                }
                ?>
</div>
<br class="clearfix" />
<div id="footer"><a href="<?=$this->baseUrl()?>/group/imprint/"><?=$this->translate('imprint_disclaimer')?></a><br />
Code &copy; 2010 by Hikaru-Shindo<br />
Design &copy; 2010 by punkid</div>
</div>
</body>
</html>
