<?php

/**
 * News_Model_Comment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    FansubCMS
 * @subpackage Models
 * @author     FansubCMS Dev Team <hikaru@fansubcode.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class News_Model_Comment extends News_Model_Base_Comment
{
    /**
     * Die Settermethode für URL
     * @author Hikaru-Shindo <hikaru@animeownage.de>
     * @param string $url
     */
    public function setUrl ($url)
    {
        $url = urldecode($url);
        if (! stristr($url, 'http://') && ! stristr($url, 'https://') &&
         ! empty($url))
            $url = 'http://' . $url;
        $this->_set('url', $url);
    }
    /**
     * Die Settermethode für Comments
     * @author Hikaru-Shindo <hikaru@animeownage.de>
     * @param string $comment
     */
    public function setComment ($comment)
    {
        $comment = str_replace('\xC2\xA0', ' ', $comment); // nbsp ersetzen durch normanel space
        $comment = trim($comment, '\n'); // string trimmen
        $this->_set('comment', $comment);
    }
    public function checkSpam ($mark = true)
    {
        $a = new FansubCMS_Validator_Akismet();
        $a = $a->getAkismet();
        $a->setCommentAuthor($this->author);
        $a->setCommentAuthorEmail($this->email);
        $a->setCommentAuthorURL($this->url);
        $a->setCommentContent($this->comment);
        $a->setUserIP($this->ip);
        $a->setReferrer(getenv('HTTP_REFERER'));
        $status = $a->isCommentSpam();
        if ($mark === true) {
            $status ? $set = 'yes' : $set = 'no';
            $this->_set('spam', $set);
        }
        return $status;
    }
}