<?php

/**
 * News_Model_CommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class News_Model_CommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object News_Model_CommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('News_Model_Comment');
    }
    
    public function getSpamPaginator ()
    {
        $q = $this->createQuery();
        $q->where('spam = ?', 'yes');
        $adapter = new FansubCMS_Paginator_Adapter_Doctrine($q);
        return new Zend_Paginator($adapter);
    }
}